[repository]
name = "WopiHost"

[exclude]
# Build artifacts and generated files
paths = [
  # Build outputs
  "**/bin/**",
  "**/obj/**", 
  "**/Debug/**",
  "**/Release/**",
  "**/x64/**",
  "**/x86/**",
  "**/build/**",
  "**/bld/**",
  
  # Visual Studio files
  "**/.vs/**",
  "**/*.user",
  "**/*.suo",
  "**/*.sln.docstates",
  
  # Test results
  "**/TestResults/**",
  "**/TestResult.xml",
  "**/*.trx",
  
  # Coverage files
  "**/*.coverage",
  "**/coverage.xml",
  "**/coverage.json",
  "**/*.opencover.xml",
  
  # NuGet packages
  "**/packages/**",
  "**/*.nupkg",
  
  # Generated code
  "**/Generated_Code/**",
  "**/AssemblyInfo.cs",
  "**/GlobalAssemblyInfo.cs",
  "**/TemporaryGeneratedFile_*.cs",
  
  # Documentation
  "**/DocProject/**",
  
  # Temp and cache files
  "**/temp/**",
  "**/.history/**",
  "**/artifacts/**",
  "**/BenchmarkDotNet.Artifacts/**",
  
  # Third-party dependencies  
  "**/Microsoft.CobaltCore/**",
  
  # Image and other assets
  "**/img/**",
  
  # Development container and infrastructure
  "**/.devcontainer/**",
  "**/infra/**",
  
  # Sample code (if not part of main analysis)
  "**/sample/**"
]

[tools.csharp]
enabled = true

[tools.security]
enabled = true

[tools.duplication]
enabled = true

[plugins.dotnet]
enabled = true 