name: ðŸ› Bug Report
description: Create a report to help us improve WopiHost
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which Office product are you using?
      options:
        - Office Web Apps
        - Office Online Server
        - Office Online
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the Office product are you using? (e.g., 1.0.0, 2.0.0)
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you running?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of your operating system? (e.g., Windows 11, macOS 14.0, Ubuntu 22.04)
      placeholder: "e.g., Windows 11, macOS 14.0, Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: nuget-package
    attributes:
      label: NuGet Package
      description: Which WopiHost NuGet package are you using? (e.g., WopiHost.Core, WopiHost.FileSystemProvider)
      placeholder: "e.g., WopiHost.Core 1.0.0"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: "What should have happened?"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "What actually happened?"
    validations:
      required: true

  - type: checkboxes
    id: source-modification
    attributes:
      label: Source Modification
      description: Have you modified the source code?
      options:
        - label: I have modified the source code of WopiHost
          required: false

  - type: textarea
    id: modification-details
    attributes:
      label: Modification Details
      description: If you modified the source, please describe how (attach your source, link your fork)
      placeholder: "Note: I can't support significantly modified sources unless you sponsor the project."
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Drag and drop images here or paste image URLs"
    validations:
      required: false

  - type: textarea
    id: stack-trace
    attributes:
      label: Stack Trace
      description: If applicable, provide the full stack trace
      placeholder: "Paste the full stack trace here"
    validations:
      required: false

  - type: textarea
    id: event-viewer-logs
    attributes:
      label: Event Viewer Logs
      description: If applicable, provide logs from Event Viewer -> Applications and Service Logs -> Office Web Apps
      placeholder: "Paste relevant logs here"
    validations:
      required: false

  - type: textarea
    id: checkfileinfo-response
    attributes:
      label: CheckFileInfo Response
      description: If applicable, provide the CheckFileInfo response
      placeholder: "Paste the CheckFileInfo response here"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Contribution & Ownership

  - type: textarea
    id: attempted-fixes
    attributes:
      label: What I Tried
      description: What have you tried to fix or work around this issue?
      placeholder: |
        - I tried [specific approach]
        - I searched for similar issues
        - I checked the documentation
        - I tried [other approach]
    validations:
      required: false

  - type: dropdown
    id: contribution-intent
    attributes:
      label: Contribution Intent
      description: How would you like to contribute to resolving this issue?
      options:
        - I'd like to contribute with a PR to fix this
        - I'd like this to be implemented for me by someone else
        - I can help with testing once a fix is available
        - I can provide more information if needed
        - I'm just reporting the issue
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "Any other information that might be helpful"
    validations:
      required: false
