<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\WopiHost.Core\WopiHost.Core.csproj" />
		<ProjectReference Include="..\WopiHost.Abstractions.Testing\WopiHost.Abstractions.Testing.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Controllers\" />
	  <Folder Include="Infrastructure\" />
	  <Folder Include="Security\Authentication\" />
	  <Folder Include="Security\Authorization\" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
	  <PackageReference Include="Moq" />
	</ItemGroup>
</Project>
