<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\WopiHost.RedisLockProvider\WopiHost.RedisLockProvider.csproj" />
		<ProjectReference Include="..\WopiHost.Abstractions.Testing\WopiHost.Abstractions.Testing.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Testcontainers.Redis" />
	</ItemGroup>
</Project>
