using System.Diagnostics.CodeAnalysis;
using System.Net;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Hosting.Server.Features;
using WopiHost.Abstractions;
using WopiHost.Discovery;
using WopiHost.FileSystemProvider;
using WopiHost.Web;
using WopiHost.Web.Models;

namespace WopiHost.SmokeTests.Fixtures;

/// <summary>
/// Hosts <c>sample/WopiHost.Web</c> behind a real Kestrel listener on a random localhost port so
/// Playwright (which drives a browser) can reach it.
/// </summary>
/// <remarks>
/// We don't use <c>WebApplicationFactory&lt;T&gt;</c> here because its <c>StartServer</c>
/// hard-casts <c>IServer</c> to <c>TestServer</c>, which crashes the moment we swap in Kestrel.
/// Instead we replicate the relevant pieces of <c>sample/WopiHost.Web/Program.cs</c>
/// (controllers, discovery, storage provider) and bind Kestrel ourselves. The DI wiring is
/// intentionally minimal — just enough to make the Index page render — and the
/// <see cref="IDiscoverer"/> registration is replaced with a <see cref="FakeDiscoverer"/> so
/// the controller doesn't try to fetch discovery XML from an unreachable test hostname.
/// </remarks>
public sealed class WebSampleFactory : IDisposable, IAsyncDisposable
{
    private readonly WebApplication _app;

    /// <summary>Loopback URL the listener bound to.</summary>
    [SuppressMessage("Design", "CA1056:URI-like properties should not be strings",
        Justification = "The only consumer is Playwright's GotoAsync(string), which takes a string. Wrapping as Uri here just to ToString() at every call site adds noise without a security or correctness benefit — the loopback address is a trusted, internally-generated test seam.")]
    public string ServerUrl { get; }

    public WebSampleFactory()
    {
        var builder = WebApplication.CreateBuilder();
        builder.WebHost.ConfigureKestrel(options => options.Listen(IPAddress.Loopback, 0));

        // Mirror sample/WopiHost.Web/Program.cs config — minus AddServiceDefaults (Aspire-only).
        builder.Configuration.AddInMemoryCollection(new Dictionary<string, string?>
        {
            ["Wopi:HostUrl"] = "http://wopihost.test",
            ["Wopi:ClientUrl"] = "https://office.example.test",
            ["Wopi:Discovery:NetZone"] = "ExternalHttps",
            ["Wopi:Discovery:RefreshInterval"] = "12:00:00",
            ["Wopi:StorageProvider:RootPath"] = TestPaths.WopiDocsRoot,
        });

        // The test project is the entry assembly, so MVC's default scan won't find HomeController
        // in WopiHost.Web. Plumb the assembly in explicitly. The precompiled views assembly
        // (WopiHost.Web.Views.dll, generated by Razor compilation in the Web SDK) is auto-loaded
        // via [RelatedAssemblyAttribute].
        builder.Services.AddControllersWithViews()
            .AddApplicationPart(typeof(WebSampleEntryPoint).Assembly);

        builder.Services
            .AddOptionsWithValidateOnStart<WopiOptions>()
            .Bind(builder.Configuration.GetRequiredSection(WopiOptions.SectionName))
            .ValidateDataAnnotations();

        // Faked discoverer instead of AddWopiDiscovery — avoids HTTP fetch from ClientUrl.
        builder.Services.AddSingleton<IDiscoverer, FakeDiscoverer>();

        builder.Services.AddSingleton<InMemoryFileIds>();
        builder.Services.AddScoped<IWopiStorageProvider, WopiFileSystemProvider>();

        var app = builder.Build();
        app.UseDeveloperExceptionPage();
        app.UseStaticFiles();
        app.UseRouting();
        app.MapControllerRoute(name: "default", pattern: "{controller=Home}/{action=Index}/{id?}");

        _app = app;
        _app.StartAsync().GetAwaiter().GetResult();

        var addresses = _app.Services.GetRequiredService<IServer>().Features.Get<IServerAddressesFeature>();
        ServerUrl = addresses?.Addresses.FirstOrDefault()
            ?? throw new InvalidOperationException("No address bound — Kestrel didn't start as expected.");
    }

    public void Dispose() => DisposeAsync().AsTask().GetAwaiter().GetResult();

    public async ValueTask DisposeAsync()
    {
        await _app.StopAsync();
        await _app.DisposeAsync();
    }
}
