name: Build & Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/FUNDING.yml'
      - 'LICENSE'
      - '.claude/**'

permissions:
  contents: read
  id-token: write # Required for OIDC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'        
    - name: Set Cobalt packages token
      run: echo "COBALT_PACKAGES_TOKEN=${{ secrets.COBALT_PACKAGES_TOKEN }}" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
    - name: Upload coverage to Qlty
      uses: qltysh/qlty-action/coverage@v2
      with:
        oidc: true
        files: "**/coverage.*.info"
    - name: Codecov
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    #- name: Run FOSSA scan
    #  uses: fossa-contrib/fossa-action@v1
    #  with:
    #    fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
